name: null
favicon: null
layout_spectrum: 0.46199899655766785
typography_spectrum: 0.4689159798435867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8569732389878482
  lightness: 0.7556854484137148
  saturation: 0.26436470565386117
  rhythmicContrast: 0.37484470405615866
purpose: []
