name: ENAS
favicon: null
layout_spectrum: 0.60462
typography_spectrum: 0.75253
title: One. Oneness. Connection. Connectedness. Unity. Reconnection.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#011f33'
    - '#00097c'
    - '#e3e3fe'
  brandStrength: 0.625
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
